<?php
declare( strict_types = 1 );

namespace Stubbetje\Twig\ZendForm\Renderer;

use Zend\Form\Element\Password;
use Zend\Form\ElementInterface;

class FormPassword extends FormInput
{
	public function __invoke( ElementInterface $element )
	{
		return parent::__invoke( $element ); // TODO: Change the autogenerated stub
	}
}